name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Tuist
      run: |
        bash <(curl -Ls https://install.tuist.io)
    - name: Generate project
      run: |
        tuist generate

    - name: Xcode Test
      # You may pin to the exact commit or the version.
      # uses: devbotsxyz/xcode-test@8f7f94ea653de78092a24ccc5cf6e3da59268d83
      uses: devbotsxyz/xcode-test@v1.1.0
      with:
        workspace: CatFacts.xcworkspace
        scheme: CatFactsApp
        destination: "{ platform:iOS Simulator, id:EAA7E727-5ACF-44A7-8C73-8F2D51BB389C, OS:15.2, name:iPhone 12 Pro Max }"

