name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Tuist
      run: tuist generate
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
